import type { Metadata } from "next";
import { server } from "../mocks/server";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (typeof window === "undefined") {
  server.listen();
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="max-w-[768px] m-auto relative">{children}</body>
    </html>
  );
}
