import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const { worker } = require("../mocks/browser");
worker.start();

console.log(worker);
if (typeof window !== "undefined") {
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="max-w-[768px] m-auto relative">{children}</body>
    </html>
  );
}
