import type { Metadata } from 'next';
import './globals.css';
import ClientProvider from '@/_components/ClientProvider';
import * as styles from '@/layout.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body className="max-w-[768px] max-h-[100vh] overflow-hidden m-auto relative">
				<ClientProvider>
					<div className={ styles.innerLayout }>
						{children}
					</div>
				</ClientProvider>
			</body>
		</html>
	);
}
